#!/bin/bash

function mktemp {
    if [ "${1:-}" = "-d" ];
    then
        echo "tempdir"
    else
        echo "tempfile"
    fi
}

function wget {
    echo "wget $@" >> $LIST_OF_ACTIONS
}

function mkdir {
    if [ "${1:-}" = "-p" ];
    then
        echo "$2" >> $LIST_OF_DIRECTORIES
    fi
}

function unzip {
    echo "Random rubbish from unzip"
    echo "unzip $@" >> $LIST_OF_ACTIONS
}
